version: '3.3'
services:
  api:
    image: maven:3.8.1-openjdk-17-slim
    container_name: api
    working_dir: /app
    volumes:
      - ./:/app
      - maven_cache:/root/.m2
    depends_on:
      - postgres
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  postgres:
    image: postgres:14-alpine
    container_name: api-db
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bla123x
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
volumes:
  pg_data:
  maven_cache: